services:
  - type: web
    name: telegram-bot-webhook
    env: python
    pythonVersion: 3.11.9     # ✅ أضف هذا السطر
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    autoDeploy: true
