services:
  - type: web
    name: telegram-webhook
    env: python
    plan: free
    buildCommand: "pip install -r telegram_webhook_app/requirements.txt"
    startCommand: "gunicorn telegram_webhook_app.main:app"
